name: bandwagon

# x- 是指擴充欄位，不會真的被 docker 解析使用，只是自己用的。& 則是給他一個名字給後面以 <<: *build_common 作引用
x-build-common: &build_common
  context: .
  dockerfile: docker/Dockerfile
  # 下面這些選項可以讓 buildKit 明確指定 cache 的位置。沒有用 remote cache 影響還好，但可以讓 CICD build 的路徑比較一致
  # cache_from:
  #   - type=local,src=.cache/buildx
  # cache_to:
  #   - type=local,dest=.cache/buildx,mode=max

services:
  dugout:
    build:
      <<: *build_common
      target: dugout
    image: ${DOCKER_REPO}/dugout:${DUGOUT_VERSION}
    environment:
      NODE_ENV: dev
      DEPLOY_ENV: gcp
    ports: ['80:8080']
    profiles: ['dugout']
  runner:
    build:
      <<: *build_common
      target: runner
    image: ${DOCKER_REPO}/runner:${SCOUT_VERSION}
    environment:
      NODE_ENV: dev
      DEPLOY_ENV: gcp
      REDIS_HOST: redis
    profiles: ['runner']
    depends_on:
      redis:
        condition: service_healthy
  lineup:
    build:
      <<: *build_common
      target: lineup
    image: ${DOCKER_REPO}/lineup:${SCOUT_VERSION}
    environment:
      NODE_ENV: dev
      DEPLOY_ENV: gcp
      REDIS_HOST: redis
    ports: ['80:8080']
    profiles: ['lineup']
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7
    volumes:
      - ./infra/config/redis.conf/:/usr/local/etc/redis/redis.conf
      - redis-data:/mnt/data/redis
      # docker 會管理名為 redis-data 的 volume，會跟 container 的 /data 作掛勾
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    profiles: ['lineup']

volumes:
  redis-data:
