name: bandwagon

# x- 是指擴充欄位，不會真的被 docker 解析使用，只是自己用的。& 則是給他一個名字給後面以 <<: *build_common 作引用
x-build-common: &build_common
  context: .
  dockerfile: docker/Dockerfile
  # 下面這些選項可以讓 buildKit 明確指定 cache 的位置。沒有用 remote cache 影響還好，但可以讓 CICD build 的路徑比較一致
  # cache_from:
  #   - type=local,src=.cache/buildx
  # cache_to:
  #   - type=local,dest=.cache/buildx,mode=max

services:
  dugout:
    environment:
      NODE_ENV: dev
      DEPLOY_ENV: local
      REDIS_HOST: redis
    ports: ['80:8080']
    volumes:
      - ./.cert:/.cert
      - ./scout/.env.local:/scout/.env.local
  runner:
    environment:
      NODE_ENV: dev
      DEPLOY_ENV: local
      REDIS_HOST: redis
    volumes:
      - ./.cert:/.cert
      - ./scout/.env.local:/scout/.env.local
  lineup:
    environment:
      NODE_ENV: dev
      DEPLOY_ENV: local
      REDIS_HOST: redis
    ports: ['80:8080']
    volumes:
      - ./.cert:/.cert
      - ./scout/.env.local:/scout/.env.local
  redis:
    volumes:
      - ./.temp/data:/data
      # docker 會管理名為 redis-data 的 volume，會跟 container 的 /data 作掛勾
