packages: 
  - 'piggyback'
  - 'dugout'
  - 'jumbotron'
  - 'shared'
# cause in pnpm v10, pnpm need add this option to use `pnpm deploy` command
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
 - build
