packages: 
  - 'piggyback'
  - 'dugout'
  - 'jumbotron'
  - 'shared'
# cause in pnpm v10, pnpm need add this option to use `pnpm deploy` command
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
 - build
# prevent the monorepo use other package's dependencies, it works only in local file structure but make the error when trim out other package's installed module
# but the interesting point it, it doesn't work when pnpm install, checkout this issue: https://github.com/pnpm/pnpm/issues/6893
strictPeerDependencies: true
lockfile: true # if need update pnpm-lock, manual --force option

# used to unify the package version
# overrides here makes bug below, so temporary disable it
#   24 | >>> RUN pnpm --filter=*piggyback --prod deploy  /piggyback
# ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "overrides" configuration doesn't match the value found in the lockfile

# overrides:
#   zod: ^3.25.64 # its fix issue for react naive
#   luxon: ^3.6.1 
#   "@types/luxon": ^3.6.1
#   dotenv: ^16.5.0
#   winston: ^3.17.0
#   "@google-cloud/logging-winston": ^6.0.0
#   "@google-cloud/secret-manager": ^6.0.1
#   firebase-admin: ^13.2.0
#   google-auth-library: ^9.15.1