import { describe, expect, test } from 'vitest';
import { curtGameDetailJsonSchema } from './validation';

// scout/.log/getlive/2025_cpbl_A_00358-getlive.json
const CASES = [
  {
    name: 'common',
    desc: '',
    input: {
      FieldAbbe: '大巨蛋',
      VisitingTeamName: '統一7-ELEVEn獅',
      HomeTeamName: '台鋼雄鷹',
      VisitingTeamCode: 'ADD011',
      HomeTeamCode: 'AKP011',
      GameStatus: 3,
      GameStatusChi: '比賽結束',
      VisitingTotalScore: 3,
      HomeTotalScore: 8,
      HitterName: '吳念庭',
      PitcherName: '',
      PitcherAcnt: '',
      HitterAcnt: '0000003649',
      MvpCnt: 7,
      HitCnt: 4,
      RunBattedInCnt: 2,
      ScoreCnt: 1,
      HittingCnt: 1,
      HomeRunCnt: 0,
      InningPitchedCnt: null,
      InningPitchedDiv3Cnt: null,
      StrikeOutCnt: null,
      RunCnt: null,
      MvpEnName: 'WU Nien Ting',
      VisitingClubBigImgPath:
        '/files/atts/0L021496167521474259/logo_lions_large.png',
      VisitingClubSmallImgPath:
        '/files/atts/0L021496162893869773/logo_lions.png',
      HomeClubBigImgPath: '/files/atts/0M259522042284091551/TSG-logo0912.png',
      HomeClubSmallImgPath:
        '/files/atts/0M259522048557486065/單色T-100x100.png',
      WinningPitcherName: '張誠恩',
      WinningPitcherAcnt: '0000007069',
      LosePitcherName: '郭俊麟',
      LosePitcherAcnt: '0000001260',
      CloserPitcherName: '',
      CloserPitcherAcnt: '',
      WinningType: '2',
      VisitingFirstMover: '郭俊麟',
      HomeFirstMover: '江承諺',
      VisitingFirstAcnt: '0000001260',
      HomeFirstAcnt: '0000002679',
      VisitingGameResultWCnt: 28,
      VisitingGameResultLCnt: 27,
      VisitingGameResultTCnt: 0,
      HomeGameResultWCnt: 26,
      HomeGameResultLCnt: 26,
      HomeGameResultTCnt: 2,
      MvpVisitingHomeType: '2',
      TicketingUrl: '',
      NewsCount: 1,
      VideoCount: 0,
      SId: null,
      VodUrl: '',
      LiveUrl: '',
      WeatherCode: 1,
      WeatherDesc:
        '晴。降雨機率20%。攝氏32至34度。悶熱。東南風 平均風速1-2級(每秒3公尺)。相對濕度56至63%。',
      AudienceCntBackend: 20552,
      HeadUmpire: '紀華文',
      OneBaseReferee: '林金達',
      TwoBaseReferee: '鄭惟丞',
      TrheeBaseReferee: '陳均瑋',
      LeftFieldReferee: '',
      RightFieldReferee: '',
      GameDuringTime: '031400',
      IsTemporary: null,
      CurtSeq: null,
      CurtVisitingHomeType: null,
      Briefing:
        '<p><span>技術室人員：邱景彥、許榮龍、陳俊銘<br /><br />◎統一7-ELEVEn獅 中斷對戰 台鋼雄鷹 3連勝( 2025/09/03~)<br />◎郭俊麟 跨季8連敗(2024/08/19~)、客場跨季6連敗(2024/08/30~)<br />◎台鋼雄鷹 中斷2連敗( 2025/09/26~)、中斷對戰 統一7-ELEVEn獅 3連敗( 2025/09/03~)<br />◎張誠恩 中斷3連敗(2025/05/13~)<br /></span></p>',
      StartersHtml: null,
      VisitingStatersPitcherHtml: null,
      HomeStatersPitcherHtml: null,
      VisitingStartersHtml: null,
      HomeStartersHtml: null,
      FirstSnos: [],
      VisitingScoreboards: null,
      HomeScoreboards: null,
      VisitingPitcherData: null,
      HomePitcherData: null,
      VisitingTeamData: null,
      HomeTeamData: null,
      CurtBatting: null,
      CurtHitterBattings: null,
      VisitingTeamByField: null,
      HomeTeamByField: null,
      Seq: '0000000001',
      PresentStatus: 1,
      GameDateTimeS: '2025-09-28T15:05:00',
      GameDateTimeE: '2025-09-28T18:19:00',
      FieldNo: 'F29',
      VisitingScore: 3,
      HomeScore: 8,
      AudienceCnt: 20552,
      IsFull: '0',
      GameResult: '0',
      MvpAcnt: '0000003649',
      GameWinningRbiAcnt: '0000003649',
      MultyGame: 'N',
      WindDirection: '',
      WindDirectionRmk: '',
      IsLock: '2',
      LockedId: 'bo138',
      Year: '2025',
      KindCode: 'A',
      GameSeasonCode: '2',
      GameSno: 358,
      Pkno: 'Z0346WZE',
      CreateTime: '2025-02-28T13:55:43',
      CreateUser: 'HOMKWO',
      UpdateTime: '2025-09-28T18:20:31',
      UpdateUser: 'bo138',
      Rowstamp: '14174349',
      Weather: '01',
      DayNight: 'D',
      GameDate: '2025-09-28T00:00:00',
      PreExeDate: '2025-09-28T15:05:00',
      IsGameStop: '0',
    },
  },
];


describe('curtGameDetail normalization', () => {
  test.for(CASES)('$name', ({ name, input }) => {
    expect(() => {
      curtGameDetailJsonSchema.parse(input, { reportInput: true });
    }
    ).not.toThrow();
  });
});